Build system rewrite: automatic dependencies detection implemented.

diff --git a/modules/mod_blend b/modules/mod_blend
--- a/modules/mod_blend
+++ b/modules/mod_blend
@@ -1,19 +1,24 @@
 #!/bin/bash
 
-if [[ $FORMAT == 'mpg' ]]; then
-cat >> Makefile << EOF
-$RENDERPATH: $RENDERPATH/file.lst
-	#TODO: ffmpeg stuff
-EOF
-RENDERPATH="$(echo $RENDERPATH | sed -e 's|\.$FORMAT$||').png"
-FORMAT='png'
-fi
+deps(){
+	if [ ! -z $1 ]; then 
+		TARGET=$1
+	fi
+	pushd `dirname $TARGET` > /dev/null
+	
+	SCRIPTPATH=$(cd `dirname $0`; pwd)/mod_blend_deps.py
+	blender -b `basename $TARGET` -P $SCRIPTPATH 2>&1 | grep -E "^dependency: " | sed -e 's/^dependency: //' | 	while read LINE; do
+		echo $LINE
+		if ( echo $LINE | grep -E '.blend$' >/dev/null); then
+			deps $LINE
+		fi
+	done
+	popd >/dev/null
+}
 
-BLENDERFORMAT=`echo $FORMAT | tr '[:lower:]' '[:upper:]'`
-RENDERSCRIPT="$(echo $RENDERPATH | sed -e 's|\.$FORMAT$||').py"
-
-[ ! -f $RENDERSCRIPT ] || rm -rf $RENDERSCRIPT
-cat >> $RENDERSCRIPT << EOF
+renderscript(){
+	[ ! -d `dirname $RENDERSCRIPT` ] || mkdir -p `dirname $RENDERSCRIPT`
+	cat > $RENDERSCRIPT << EOF
 from Blender import Scene, Object
 import sys
 
@@ -24,7 +29,7 @@ def main():
 		rend.saveBuffers = True
 		rend.compositeFree = True
 		
-		rend.oversampling = True
+		rend.oversampling = $OSA
 		
 		rend.OSALevel = 8
 		
@@ -42,9 +47,14 @@ def main():
 	#rend.enablePremultiply()
 	
 	rend.enableRGBAColor()
+EOF
+	# Get image dimensions from file if it's unspecified
 	
-	rend.sizeX = $WIDTH
-	rend.sizeY = $HEIGHT
+	
+	[ -z $WIDTH ] || echo "	rend.sizeX = $WIDTH" >> $RENDERSCRIPT
+	[ -z $HEIGHT ] || echo "	rend.sizeY = $HEIGHT" >> $RENDERSCRIPT
+	
+	cat >> $RENDERSCRIPT << EOF
 	
 	rend.xParts = 4
 	rend.yParts = 4
@@ -64,32 +74,59 @@ def main():
 if __name__ == '__main__':
 	main()
 EOF
+}
 
-if [ ! -z $SINGLE ]; then
-	RANGE="-f $SINGLE"
-	OUTPUT="\`pwd\`/${RENDERPATH}-######"
-	echo "$RENDERPATH: $TARGET $DEPS" >> Makefile
-	echo "	rm -rf $RENDERPATH" >> Makefile
-	echo "	blender -b $TARGET -S Scene -P \`pwd\`/$RENDERSCRIPT -o $OUTPUT -x 0 -F $BLENDERFORMAT -t 0 $RANGE" >> Makefile
-	echo "	mv ${RENDERPATH}-`printf %06d $SINGLE` $RENDERPATH" >> Makefile
-else
-	RANGE="-a"
-	OUTPUT="\`pwd\`/$RENDERPATH/file"
-	echo "$RENDERPATH: $RENDERPATH/file.lst" >> Makefile
-	echo ".PHONY: $RENDERPATH" >> Makefile
-	echo "$RENDERPATH/file.lst: $TARGET $DEPS" >> Makefile
-	echo "	rm -rf $RENDERPATH" >> Makefile
-	echo "	mkdir -p $RENDERPATH" >> Makefile
-	echo "	blender -b $TARGET -S Scene -P \`pwd\`/$RENDERSCRIPT -o $OUTPUT -x 1 -F $BLENDERFORMAT -t 0 $RANGE" >> Makefile
-	echo "	echo "FPS $FPS" > $RENDERPATH/file.lst" >> Makefile
-	echo "	( cd $RENDERPATH; ls -1 *.$FORMAT >> file.lst )" >> Makefile
+rules(){
+	if [[ $FORMAT == 'mpg' ]]; then
+		if ! ( which ffmpeg > /dev/null 2>&1 ); then
+			echo "   FATAL: Can't find 'ffmpeg' binary!" >&2
+			exit 1
+		fi
+		cat >> $MAKEFILE << EOF
+$RENDERPATH: $RENDERPATH/file.lst
+	#TODO: ffmpeg stuff
+EOF
+		RENDERPATH="$(echo $RENDERPATH | sed -e 's|\.$FORMAT$||').png"
+		FORMAT='png'
+	fi
+	
+	OSA="True"
+	BLENDERFORMAT=`echo $FORMAT | tr '[:lower:]' '[:upper:]'`
+	RENDERSCRIPT="$(echo $RENDERPATH | sed -e 's|\.$FORMAT$||').py"
+
+	renderscript
+
+	if [ ! -z $SINGLE ]; then
+		RANGE="-f $SINGLE"
+		OUTPUT="\`pwd\`/${RENDERPATH}-######"
+		echo "$RENDERPATH: $TARGET $DEPS" >> $MAKEFILE
+		echo "	rm -rf $RENDERPATH" >> $MAKEFILE
+		echo "	blender -b $TARGET -S Scene -P \`pwd\`/$RENDERSCRIPT -o $OUTPUT -x 0 -F $BLENDERFORMAT -t 0 $RANGE" >> $MAKEFILE
+		echo "	mv ${RENDERPATH}-`printf %06d $SINGLE` $RENDERPATH" >> $MAKEFILE
+	else
+		RANGE="-a"
+		OUTPUT="\`pwd\`/$RENDERPATH/file"
+		echo "$RENDERPATH: $RENDERPATH/file.lst" >> $MAKEFILE
+		echo ".PHONY: $RENDERPATH" >> $MAKEFILE
+		echo "$RENDERPATH/file.lst: $TARGET $DEPS" >> $MAKEFILE
+		echo "	rm -rf $RENDERPATH" >> $MAKEFILE
+		echo "	mkdir -p $RENDERPATH" >> $MAKEFILE
+		echo "	blender -b $TARGET -S Scene -P \`pwd\`/$RENDERSCRIPT -o $OUTPUT -x 1 -F $BLENDERFORMAT -t 0 $RANGE | grep -E '^Saved: '" >> $MAKEFILE
+		echo "	echo "FPS $FPS" > $RENDERPATH/file.lst" >> $MAKEFILE
+		echo "	( cd $RENDERPATH; ls -1 *.$FORMAT >> file.lst )" >> $MAKEFILE
+	fi
+
+	echo "$RENDERPATH-clean:" >> $MAKEFILE
+	if [[ $FORMAT == 'mpg' ]]; then
+		echo "	rm -f $(echo $RENDERPATH | sed -e 's|\.$FORMAT$||').mpg" >> $MAKEFILE
+	fi
+	echo "	rm -rf $RENDERPATH" >> $MAKEFILE
+	echo "	rm -rf $RENDERSCRIPT" >> $MAKEFILE
+}
+
+if ! ( which blender > /dev/null 2>&1 ); then
+	echo "   FATAL: Can't find 'blender' binary!" >&2
+	exit 1
 fi
 
-echo "	touch `dirname $RENDERPATH`/.$FORMAT" >> Makefile # This line is mandatory here
-
-echo "$RENDERPATH-clean:" >> Makefile
-if [[ $FORMAT == 'mpg' ]]; then
-	echo "	rm -f $(echo $RENDERPATH | sed -e 's|\.$FORMAT$||').mpg" >> Makefile
-fi
-echo "	rm -rf $RENDERPATH" >> Makefile
-echo "	rm -rf $RENDERSCRIPT" >> Makefile
+$1 $2
diff --git a/modules/mod_sif b/modules/mod_sif
--- a/modules/mod_sif
+++ b/modules/mod_sif
@@ -1,25 +1,55 @@
 #!/bin/bash
 
-if [[ $FORMAT == 'mpg' ]]; then
-cat >> Makefile << EOF
+deps(){
+	if [ ! -z $1 ]; then 
+		TARGET=$1
+	fi
+	if ! ( which strace > /dev/null 2>&1 ); then
+		echo "   FATAL: Can't find 'strace' binary!" >&2
+		exit 1
+	fi
+	pushd `dirname "$TARGET"`>/dev/null
+	ABSTARGET=`pwd`/`basename $TARGET`
+	popd >/dev/null
+	strace -f -eopen -o $MAKEFILE.sif synfig -t null -w 1 -h 1 -Q 10 -b $TARGET >/dev/null 2>&1
+	cat $MAKEFILE.sif | grep -E '.(jpg|png|sif|sifz|lst)", O_RDONLY' | while read LINE; do
+		LINE=`echo $LINE | sed -e 's/^[0-9]* open("//' | sed -e 's/", O_RDONLY.*) =.*$//'`
+		pushd `dirname "$LINE"`>/dev/null
+		[[ `pwd`/`basename $LINE` == $ABSTARGET ]] || echo $LINE
+		popd >/dev/null
+	done
+	rm -f $MAKEFILE.sif
+}
+
+rules(){
+	if [[ $FORMAT == 'mpg' ]]; then
+		if ! ( which ffmpeg > /dev/null 2>&1 ); then
+			echo "   FATAL: Can't find 'ffmpeg' binary!" >&2
+			exit 1
+		fi
+		cat >> $MAKEFILE << EOF
 $RENDERPATH.mpg: $RENDERPATH/file.lst
 	#TODO: ffmpeg stuff
 EOF
-RENDERPATH="$(basename $RENDERPATH .$FORMAT).png"
-FORMAT='png'
-fi
+	RENDERPATH="$(basename $RENDERPATH .$FORMAT).png"
+	FORMAT='png'
+	fi
+	
+	# Get image dimensions from file if it's unspecified
+	[ -z $WIDTH ] && OPTWIDTH="" || OPTWIDTH="-w $WIDTH"
+	[ -z $HEIGHT ] && OPTHEIGHT="" || OPTHEIGHT="-h $HEIGHT"
 
-if [ ! -z $SINGLE ]; then
-	RANGE="--time $SINGLE"
-	OUTPUT="$RENDERPATH"
-	cat >> Makefile << EOF
+	if [ ! -z $SINGLE ]; then
+		RANGE="--time ${SINGLE}f"
+		OUTPUT="$RENDERPATH"
+		cat >> $MAKEFILE << EOF
 $RENDERPATH: $TARGET $DEPS
 	rm -rf $RENDERPATH
-	synfig -t $FORMAT -o $OUTPUT $RANGE -w $WIDTH -h $HEIGHT $TARGET
+	synfig -t $FORMAT -o $OUTPUT $RANGE $OPTWIDTH $OPTHEIGHT $TARGET
 EOF
-else
-	OUTPUT="$RENDERPATH/file.$FORMAT"
-	cat >> Makefile << EOF
+	else
+		OUTPUT="$RENDERPATH/file.$FORMAT"
+		cat >> $MAKEFILE << EOF
 $RENDERPATH: $RENDERPATH/file.lst
 .PHONY: $RENDERPATH
 $RENDERPATH/file.lst: $TARGET $DEPS
@@ -29,13 +59,19 @@ $RENDERPATH/file.lst: $TARGET $DEPS
 	echo "FPS $FPS" > $RENDERPATH/file.lst
 	( cd $RENDERPATH; ls -1 *.$FORMAT >> file.lst )
 EOF
+	fi
+
+	echo "$RENDERPATH-clean:" >> $MAKEFILE
+	echo "	rm -rf $RENDERPATH" >> $MAKEFILE
+	if [[ $FORMAT == 'mpg' ]]; then
+		RENDERPATH="$(basename $RENDERPATH .$FORMAT).mpg"
+		echo "	rm -f $RENDERPATH.mpg" >> $MAKEFILE
+	fi
+}
+
+if ! ( which synfig > /dev/null 2>&1 ); then
+	echo "   FATAL: Can't find 'synfig' binary!" >&2
+	exit 1
 fi
 
-echo "	touch `dirname $RENDERPATH`/.$FORMAT" >> Makefile # This line is mandatory here
-
-echo "$RENDERPATH-clean:" >> Makefile
-echo "	rm -rf $RENDERPATH" >> Makefile
-if [[ $FORMAT == 'mpg' ]]; then
-	RENDERPATH="$(basename $RENDERPATH .$FORMAT).mpg"
-	echo "	rm -f $RENDERPATH.mpg" >> Makefile
-fi
+$1 $2
diff --git a/remake b/remake
--- a/remake
+++ b/remake
@@ -13,6 +13,21 @@ popd  > /dev/null
 #SCRIPT_PATH=$(cd `dirname $0`; pwd)
 #REPOROOT=$(dirname `git rev-parse --git-dir`)
 
+usage()
+{
+cat << EOF
+usage: $0 [options] file [action]
+
+This script generates Makefile and renders your 
+animation project taking all dependencies into 
+account.
+
+OPTIONS:
+   -h      Show this message
+   -k      Keep Makefile so you can re-invoke rendering by typing 'make'
+EOF
+}
+
 relpath(){
 	if [[ "$1" == "$2" ]]
 	then
@@ -67,10 +82,10 @@ mod_norender(){
 
 get_project_root() {
 	if [ -f ./remake.conf ]; then
-		pwd
+		pwd -P
 	else
-		if [[ `pwd` == '/' ]]; then
-			echo "ERROR: Not a 'remake' project."
+		if [[ `pwd -P` == '/' ]]; then
+			echo "   ERROR: Not a 'remake' project." 1>&2
 			exit
 		fi
 		pushd .. >/dev/null
@@ -79,202 +94,180 @@ get_project_root() {
 	fi
 }
 
+write_rules(){
+	pushd `dirname $1` >/dev/null
+	PROJECTROOT=`get_project_root`
+	RENDERPREFIX=$(pwd -P | sed -e "s|$PROJECTROOT||")
+	[ -d $PROJECTROOT/render${RENDERPREFIX} ] || mkdir -p $PROJECTROOT/render${RENDERPREFIX}
+	TARGETDIR=`pwd -P`
+	popd  >/dev/null
+	
+	CONFIGPATH=$(relpath `pwd -P` $PROJECTROOT/remake.conf)
+	
+	# Ensure that render dir ignored by git
+	[ -e $PROJECTROOT/.gitignore ] || touch $PROJECTROOT/.gitignore
+	( cat $PROJECTROOT/.gitignore | egrep "render/\*" > /dev/null ) || ( echo "render/*" >> $PROJECTROOT/.gitignore )
+
+	TARGET=$(relpath `pwd -P` $TARGETDIR)/`basename $1`
+	EXT=${TARGET##*.}
+	
+	# Re-reading config
+	. $PROJECTROOT/remake.conf
+	
+	# Looking for extra settings
+	if [ -e ${TARGET}.conf ]; then
+		. ${TARGET}.conf
+	fi
+	
+	RENDERPATH="$(relpath `pwd -P` $PROJECTROOT/render${RENDERPREFIX})/`basename $TARGET`.$FORMAT"
+	
+	export WIDTH
+	export HEIGHT
+	export FORMAT
+	export FPS
+	export SINGLE
+	
+	export TARGET
+	export RENDERPATH
+	
+	export MAKEFILE
+	
+	
+	DEPS="$CONFIGPATH"
+	PENDINGTARGETS=''
+	echo "Retrieving deps for '$TARGET'..."
+	if [ ! -f $SCRIPT_PATH/modules/mod_$EXT ]; then
+		echo "   WARNING: Don't know how to handle file with $EXT extension."
+		echo "            Skipping."
+	else
+		bash -x $SCRIPT_PATH/modules/mod_$EXT deps
+		RAWDEPS=`bash -e $SCRIPT_PATH/modules/mod_$EXT deps`
+		# Removing duplicates
+		RAWDEPS=`echo "$RAWDEPS" | sort -u`
+		# Check for new render targets
+		if [ ! -z "$RAWDEPS" ];then
+		while read LINE; do
+			if [ -d `dirname "$LINE"` ]; then
+				pushd `dirname "$LINE"` >/dev/null
+				EXTPROJECTROOT=`get_project_root`
+				popd  >/dev/null
+			else
+				EXTPROJECTROOT=""
+			fi
+			if [[ $EXTPROJECTROOT == "" ]]; then
+				# Report files outside of the repo
+				echo "   $LINE"
+				echo "   WARNING: '$LINE' is not belongs to any project."
+				echo "            Skipping."
+			else
+				pushd `dirname "$LINE"` >/dev/null
+				DEPDIR=`pwd -P`
+				popd >/dev/null
+				LINE="$(relpath `pwd -P` $DEPDIR)/`basename "$LINE"`"
+				#LINE=$(relpath `pwd` $LINE)
+				echo "   $LINE"
+				if ( echo $DEPDIR | grep -E "^${EXTPROJECTROOT}/render/" > /dev/null ); then
+					
+					#pushd `dirname $LINE` >/dev/null
+					#DEPDIR=`pwd`
+					#popd >/dev/null
+					#DEP=$(relpath `pwd` $DEPDIR)/`basename $LINE`
+					LINE=`echo "$LINE"| sed -e "s/ /\\\\ /g"`
+					DEPS='$DEPS $LINE'
+					
+					echo "   INFO: Dependency '$LINE' defines another target."
+					
+					TARGETCANDIDATE=`echo $DEPDIR/$(basename "$LINE") | sed -e "s|\.$FORMAT$||" | sed -e "s|^${EXTPROJECTROOT}/render/|${EXTPROJECTROOT}/|"`
+					if [ ! -e $TARGETCANDIDATE ]; then
+						echo "   INFO: Trying to fix '$TARGETCANDIDATE' to '`dirname $TARGETCANDIDATE`'."
+						TARGETCANDIDATE=`dirname $TARGETCANDIDATE`
+						if [ ! -e $TARGETCANDIDATE ]; then
+							echo "   ERROR: Not found!"
+						else
+							echo "         Successfull."
+						fi
+					fi
+					
+					if [ -e $TARGETCANDIDATE ]; then
+						PENDINGTARGETS="$PENDINGTARGETS $TARGETCANDIDATE"
+					fi
+				else
+					if [ ! -e "$LINE" ]; then
+						# Report non-existing files
+						echo "   WARNING: '$LINE' is not exists and not produced by any target."
+						echo "            Skipping."
+					else
+						#pushd `dirname $LINE` >/dev/null
+						#DEPDIR=`pwd`
+						#popd >/dev/null
+						#DEPS="$DEPS $(relpath `pwd` $DEPDIR)/`basename $LINE`"
+						LINE=`echo "$LINE"| sed -e "s/ /\\\\ /g"`
+						DEPS="$DEPS $LINE"
+					fi
+				fi
+			fi
+		done < <( echo "$RAWDEPS" )
+		fi
+		
+		export DEPS
+		
+		bash -e $SCRIPT_PATH/modules/mod_$EXT rules
+		
+		echo ".PHONY: $RENDERPATH-clean" >> $MAKEFILE
+		echo "clean: $RENDERPATH-clean" >> $MAKEFILE
+		
+		for TARGET in $PENDINGTARGETS;do
+			# check if rules for this target are already written
+			( cat $MAKEFILE | grep -E "^$TARGET:" >/dev/null ) || write_rules $TARGET
+		done
+	fi
+}
+
+OPT_KEEP=0
+while getopts "hk" OPTION
+do
+     case $OPTION in
+         h)
+             usage
+             exit 1
+             ;;
+         k)
+             OPT_KEEP=1
+             ;;
+         ?)
+             usage
+             exit
+             ;;
+     esac
+done
+
+shift $(($OPTIND - 1))
+
+if [ -z $1 ]; then
+	echo
+	echo "ERROR: Please specify filename to render. Aborting." >&2
+	echo
+	usage
+	exit 1
+fi
+
+pushd `dirname $1`>/dev/null
 PROJECTROOT=`get_project_root`
+popd >/dev/null
+
+[ -d ${PROJECTROOT}/render/tmp ] || mkdir -p ${PROJECTROOT}/render/tmp
+MAKEFILE=${PROJECTROOT}/render/tmp/Makefile.$$
+[ ! -e $MAKEFILE ] || rm $MAKEFILE
+touch $MAKEFILE
 
 #creating render dir
 #[ -d $REPOROOT/render ] || mkdir -p $REPOROOT/render
 
-#ensure that render dir ignored by git
-[ -e $PROJECTROOT/.gitignore ] || touch $PROJECTROOT/.gitignore
-( cat $PROJECTROOT/.gitignore | egrep "render/\*" > /dev/null ) || ( echo "render/*" >> $PROJECTROOT/.gitignore )
+write_rules $1
+echo ".PHONY: clean" >> $MAKEFILE
 
-if [ -f ./Makefile.re ]; then
-	[ ! -f Makefile ] || rm Makefile
-	touch Makefile
-	
-	while read LINE; do
-		#Re-reading config
-		. $PROJECTROOT/remake.conf
-		CONFIGPATH=$(relpath `pwd` $PROJECTROOT/remake.conf)
-		
-		TARGET=${LINE%%:*}'|'
-		OPTIONS=${TARGET#*|}
-		TARGET=${TARGET%%|*}
-		echo "-> $TARGET"
-		
-		I=1
-		FIELD=`echo $OPTIONS | cut -d '|' -f $I`
-		while ! [ -z $FIELD ]; do
-			NAME=${FIELD%=*}
-			VALUE=${FIELD#*=}
-			case $NAME in
-				'NORENDER')
-					VALUE=1
-					NORENDER=$VALUE
-					;;
-				'SINGLE')
-					SINGLE=$VALUE
-					;;
-				'WIDTH')
-					WIDTH=$VALUE
-					;;
-				'HEIGHT')
-					HEIGHT=$VALUE
-					;;
-				'FORMAT')
-					FORMAT=$VALUE
-					;;
-			esac
-			echo $NAME $VALUE
-			
-			I=`expr $I + 1`
-			FIELD=`echo $OPTIONS | cut -d '|' -f $I`
-		done
-		
-		RENDERPREFIX=$(pwd | sed -e "s|$PROJECTROOT||")
-		[ -d $PROJECTROOT/render${RENDERPREFIX} ] || mkdir -p $PROJECTROOT/render${RENDERPREFIX}
-		RENDERPATH="$(relpath `pwd` $PROJECTROOT/render${RENDERPREFIX})/$TARGET"
-		# Target alias
-		ALIASCODE="${RENDERPATH}: $RENDERPATH.${FORMAT}\n.PHONY: ${RENDERPATH}\n"
-		# Real target
-		RENDERPATH=$RENDERPATH.$FORMAT
-		EXT=${TARGET##*.}
-		
-		RAWDEPS=${LINE#*:}
-		DEPS=""
-		DEPSCODE=""
-		DEPSCLEANCODE=""
-		for DEPENDENCY in $RAWDEPS; do
-			#checking if dependency is external
-			EXTERNAL=0
-			echo "--> Checking '${DEPENDENCY}'..."
-			if ( [ -d ${DEPENDENCY} ] && [ -e ${DEPENDENCY}/Makefile.re ] ); then
-				EXTERNAL=1
-				DEPDIR=${DEPENDENCY}
-				DEPFILE=''
-				DEPEXT=$FORMAT
-			else 
-				if (( echo ${DEPENDENCY} | grep -E "/" ) && ( cat "`dirname ${DEPENDENCY}`/Makefile.re" | grep -E "^${DEPENDENCY}(\|.*)*:" >/dev/null ) ); then
-					EXTERNAL=1
-					DEPDIR=`dirname ${DEPENDENCY}`
-					DEPFILE=`basename ${DEPENDENCY}`
-					# determining extension
-					DEPEXT=$FORMAT
-					LINE=$(cat "`dirname ${DEPENDENCY}`/Makefile.re" | grep -E "^${DEPENDENCY}(\|.*)*:")
-					FIELDS=${LINE%%:*}'|'
-					FIELDS=${FIELDS#*|}
-					I=1
-					FIELDS=`echo $FIELDS | cut -d '|' -f $I`
-					while ! [ -z $FIELDS ]; do
-						NAME=${FIELD%=*}
-						VALUE=${FIELD#*=}
-						if [[ $NAME == 'FORMAT' ]];then
-								DEPEXT=$VALUE
-								FIELDS=""
-						else
-							I=`expr $I + 1`
-							FIELDS=`echo $FIELDS | cut -d '|' -f $I`
-						fi
-					done
-					# determining extension done
-				fi
-			fi
-			if [[ $EXTERNAL == 1 ]];then
-				echo "---> External dependency detected."
-				pushd $DEPDIR >/dev/null
-				EXTPROJECTROOT=`get_project_root`
-				RENDERPREFIX=$(pwd | sed -e "s|$EXTPROJECTROOT||")
-				REMAKEBINARY=$(relpath `pwd` $SCRIPT_PATH/remake)
-				popd >/dev/null
-				EXTRENDERPATH="$(relpath `pwd` $EXTPROJECTROOT/render${RENDERPREFIX})/$DEPFILE.$DEPEXT"
-				DEPS="$DEPS ${EXTRENDERPATH}"
-				#invoke child process as dependency
-				
-				DEPSCODE="${DEPSCODE}	cd $DEPDIR && bash -e $REMAKEBINARY $DEPFILE\n"
-				DEPSCLEANCODE="${DEPSCLEANCODE}	cd $DEPDIR && bash -e $REMAKEBINARY ${DEPFILE}.clean\n"
-			else
-				if ( cat Makefile.re | grep -E "^${DEPENDENCY}(\|.*)*:" >/dev/null ); then
-					pushd `dirname $DEPENDENCY` >/dev/null
-					RENDERPREFIX=$(pwd | sed -e "s|$PROJECTROOT||")
-					popd >/dev/null
-					DEPS="$DEPS $(relpath `pwd` $PROJECTROOT/render${RENDERPREFIX})/$DEPENDENCY"
-					#[ ! -d $DEPENDENCY ] || DEPS="$DEPS $DEPENDENCY"
-				else
-					DEPS="$DEPS $DEPENDENCY"
-				fi
-			fi
-		done
-		DEPS="$DEPS $CONFIGPATH Makefile.re"
-		
-		export WIDTH
-		export HEIGHT
-		export FORMAT
-		export FPS
-		export SINGLE
-		
-		export TARGET
-		export DEPS
-		export RENDERPATH
-		
-		if ( ( echo $TARGET | grep -E "/" >/dev/null) || [ -d $TARGET ] ); then
-			echo "WARNING: Target '$TARGET' is redundant."
-			#mod_external
-		else
-			printf "$ALIASCODE" >> Makefile
-			if [ ! -z $NORENDER ];then
-				mod_norender
-			else
-				if [ -f $SCRIPT_PATH/modules/mod_$EXT ]; then
-					bash -e $SCRIPT_PATH/modules/mod_$EXT
-				else
-					echo "WARNING: Don't know how to handle file with $EXT extension."
-					echo "         Skipping."
-				fi
-			fi
-			CLEANTARGETS="$CLEANTARGETS ${RENDERPATH}.clean"
-			# Adding implicit targets
-			if [ ! -z "$DEPSCODE" ];then
-				DEPSTARGETS="${TARGET}.deps"
-				echo "${TARGET}.deps:" >> Makefile
-				printf "${DEPSCODE}" >> Makefile
-			fi
-			if [ ! -z "$DEPSCLEANCODE" ];then
-				echo "${TARGET}.deps.clean:" >> Makefile
-				printf "${DEPSCLEANCODE}" >> Makefile
-				CLEANTARGETS="$CLEANTARGETS ${TARGET}.deps.clean"
-			fi
-		fi
-	done <  Makefile.re
-	
-	#clean action
-	echo >> Makefile
-	echo ".deps: $DEPSTARGETS" >> Makefile
-	echo ".clean: $CLEANTARGETS" >> Makefile
-	echo "	rm -rf $(relpath `pwd` $PROJECTROOT/render${RENDERPREFIX}/)" >> Makefile
-	echo ".PHONY: $CLEANTARGETS $DEPSTARGETS" >> Makefile
-	
-	#include customs
-	[ -f Makefile.in ] && cat Makefile.in >> Makefile
-fi
-
-if [ ! -z $1 ]; then
-	if [[ $1 == 'clean' ]]; then
-		ACTION='.clean'
-	else
-		if ( cat Makefile.re | grep -E "^$1(\|.*)*:" >/dev/null ); then
-			pushd `dirname $1` >/dev/null
-			RENDERPREFIX=$(pwd | sed -e "s|$PROJECTROOT||")
-			popd >/dev/null
-			FORMAT=$ARGFORMAT
-			ACTION=$(relpath `pwd` $PROJECTROOT/render${RENDERPREFIX})/$TARGET
-			[ -d $1 ] && mkdir -p $ACTION || mkdir -p `dirname $ACTION`
-		else
-			echo "No rule for '$1' found."
-			exit
-		fi
-	fi
-fi
+[[ $OPT_KEEP == 0 ]] || cp -f $MAKEFILE Makefile
 
 echo "Running make..."
-make ${ACTION}.deps
-make $ACTION
+make -f $MAKEFILE $2
+rm -f $MAKEFILE
