Implement check() function for all modules.

diff --git a/modules/mod_ogg b/modules/mod_ogg
--- a/modules/mod_ogg
+++ b/modules/mod_ogg
@@ -1,8 +1,19 @@
 #!/bin/bash
 
+# ==== Utility functions ====
+
 escape()
 {
 echo "$1"| sed -e "s/ /\\\\\\ /g"
+}
+
+# ==== Module functions ====
+
+check(){
+	if ! ( which oggdec > /dev/null 2>&1 ); then
+		echo "   FATAL: Can't find 'oggdec' binary!" >&2
+		exit 1
+	fi
 }
 
 format(){
@@ -24,10 +35,5 @@ EOF
 	echo "`escape "$RENDERPATH-clean:"`" >> "$MAKEFILE"
 	echo "	rm -rf \"$RENDERPATH\"" >> "$MAKEFILE"
 }
-
-if ! ( which oggdec > /dev/null 2>&1 ); then
-	echo "   FATAL: Can't find 'oggdec' binary!" >&2
-	exit 1
-fi
 
 $1 "$2"
diff --git a/modules/mod_pcl b/modules/mod_pcl
--- a/modules/mod_pcl
+++ b/modules/mod_pcl
@@ -1,8 +1,35 @@
 #!/bin/bash
 
+# ==== Utility functions ====
+
 escape()
 {
 echo "$1"| sed -e "s/ /\\\\\\ /g"
+}
+
+# ==== Module functions ====
+
+check(){
+	export PENCILBIN=''
+	if ( which pencil > /dev/null 2>&1 ); then
+		PENCILBIN='pencil'
+	elif ( which Pencil > /dev/null 2>&1 ); then
+		PENCILBIN='Pencil'
+	else
+		echo "   FATAL: Can't find 'pencil' binary!" >&2
+		exit 1
+	fi
+
+	# Magic to check if pencil have required patches
+	DISPLAY=cumba:woomba:0.x $PENCILBIN | grep "(Morevna Branch" >/dev/null
+	PENCIL_VERSION=`echo $?`
+	if [[ $PENCIL_VERSION == 1 ]] ; then
+		echo "   FATAL: This version of Pencil doesn't supports commandline options!"
+		echo "          Please get modified version from any of the following urls:"
+		echo "           * Source: http://github.com/morevnaproject/pencil"
+		echo "           * Binaries: http://morevnaproject.org/packages"
+		exit 1
+	fi
 }
 
 format(){
@@ -53,26 +80,5 @@ rules(){
 		echo "	rm -f \"$RENDERPATH\"" >> "$MAKEFILE"
 	fi
 }
-
-export PENCILBIN=''
-if ( which pencil > /dev/null 2>&1 ); then
-	PENCILBIN='pencil'
-elif ( which Pencil > /dev/null 2>&1 ); then
-	PENCILBIN='Pencil'
-else
-	echo "   FATAL: Can't find 'pencil' binary!" >&2
-	exit 1
-fi
-
-# Magic to check if pencil have required patches
-DISPLAY=cumba:woomba:0.x $PENCILBIN | grep "(Morevna Branch" >/dev/null
-PENCIL_VERSION=`echo $?`
-if [[ $PENCIL_VERSION == 1 ]] ; then
-	echo "   FATAL: This version of Pencil doesn't supports commandline options!"
-	echo "          Please get modified version from any of the following urls:"
-	echo "           * Source: http://github.com/morevnaproject/pencil"
-	echo "           * Binaries: http://morevnaproject.org/packages"
-	exit 1
-fi
 
 $1 "$2"
diff --git a/modules/mod_sif b/modules/mod_sif
--- a/modules/mod_sif
+++ b/modules/mod_sif
@@ -1,8 +1,25 @@
 #!/bin/bash
 
+# ==== Utility functions ====
+
 escape()
 {
 echo "$1"| sed -e "s/ /\\\\\\ /g"
+}
+
+# ==== Module functions ====
+
+check(){
+	if ! ( which synfig > /dev/null 2>&1 ); then
+		echo "   FATAL: Can't find 'synfig' binary!" >&2
+		exit 1
+	fi
+	if [[ $FORMAT == 'mpg' ]]; then
+		if ! ( which ffmpeg > /dev/null 2>&1 ); then
+			echo "   FATAL: Can't find 'ffmpeg' binary!" >&2
+			exit 1
+		fi
+	fi
 }
 
 format(){
@@ -91,10 +108,6 @@ deps(){
 
 rules(){
 	if [[ $FORMAT == 'mpg' ]]; then
-		if ! ( which ffmpeg > /dev/null 2>&1 ); then
-			echo "   FATAL: Can't find 'ffmpeg' binary!" >&2
-			exit 1
-		fi
 		RENDERPATH_BASE="`echo "$RENDERPATH" | sed -e "s|\.$FORMAT$||"`"
 		echo "`escape "$RENDERPATH"`: `escape "${RENDERPATH_BASE}.png"`/file.lst" >> "$MAKEFILE"
 		echo "	ffmpeg -y -i \"${RENDERPATH_BASE}.png/file.%04d.png\" -sameq -r $FPS \"${RENDERPATH}\"" >> "$MAKEFILE"
@@ -133,10 +146,5 @@ rules(){
 		echo "	rm -f \"$RENDERPATH\"" >> "$MAKEFILE"
 	fi
 }
-
-if ! ( which synfig > /dev/null 2>&1 ); then
-	echo "   FATAL: Can't find 'synfig' binary!" >&2
-	exit 1
-fi
 
 $1 "$2"
diff --git a/modules/mod_sifz b/modules/mod_sifz
--- a/modules/mod_sifz
+++ b/modules/mod_sifz
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# ==== Module functions ====
+
 SIF_MODULE="`dirname $0`/mod_sif"
 
 export WIDTH
@@ -13,6 +15,13 @@ export TARGET
 export RENDERPATH
 
 export MAKEFILE
+
+check(){
+	if ! ( which synfig > /dev/null 2>&1 ); then
+		echo "   FATAL: Can't find 'synfig' binary!" >&2
+		exit 1
+	fi
+}
 
 format(){
 	echo $FORMAT
@@ -28,10 +37,5 @@ deps(){
 rules(){
 	bash -e $SIF_MODULE rules
 }
-
-if ! ( which synfig > /dev/null 2>&1 ); then
-	echo "   FATAL: Can't find 'synfig' binary!" >&2
-	exit 1
-fi
 
 $1 "$2"
